### PR TITLE
Adjustment to work with most recent prometheus-cpp and bazel releases

### PR DESCRIPTION
**Pull request by tolleiv**
Hi, here's all I had to adjust to build the conntrack_exporter with the most recent prometheus-cpp and bazel releases.

Hope this helps somebody.

### CODE REVIEW

**Comment by dbendelman** [comment]
Hi @tolleiv, I'm a bit embarrased that I hadn't noticed your PR back in 2020! My apologies.

@sergey-safarov just posted about a build problem in [another issue](https://github.com/hiveco/conntrack_exporter/issues/12) and I mentioned he should make a PR and I'll merge. Sergey, perhaps try using Tolleiv's PR as a starting point since it looks like it solves your issue, and if it builds please update me and I'll merge it.

Thanks!

**Comment by sergey-safarov** [comment]
I successfully compiled sources on Fedora 37 and bazel 6 on arm server.
Only required change.
```diff
diff --git a/BUILD b/BUILD
index c34568e..1d96a73 100644
--- a/BUILD
+++ b/BUILD
@@ -8,6 +8,6 @@ cc_binary(
     ],
     linkstatic=1,
     linkopts = [
-        "-l/usr/lib/x86_64-linux-gnu/libnetfilter_conntrack.so",
+        "-l netfilter_conntrack",
     ],
 )
```

**Comment by dbendelman** [comment]
@sergey-safarov ”I successfully compiled” means on the master branch or with this PR?

Also I don’t have access to a Fedora box to test and don’t want to merge hand rolled untested code. Would you mind updating this PR or making a new one? Thanks

**Comment by sergey-safarov** [comment]
With this PR.

```
commit 4e945cc6c1e93db859135696bcaed0543a2e222f (origin/tolleiv-patch-2)
Author: Tolleiv Nietsch <github@tolleiv.de>
Date:   Mon Aug 17 11:48:58 2020 +0200

    Adjustment to work with most recent prometheus-cpp and bazel releases

commit 028bf8e3c09862a53ba13ddd6d1cd41737212350 (upstream/master, origin/master, origin/HEAD)
Author: Danny Bendelman <dbendelman@users.noreply.github.com>
Date:   Wed Jul 18 17:51:25 2018 -0400

    Documented logging
```

**Comment by sergey-safarov** [comment]
Modified PR created.

**Comment by dbendelman** [comment]
Merged #14 which superceded this PR. Thanks @tolleiv & @sergey-safarov

**Pull request closed without merging**
